import type { Metadata } from "next";

// Components
import Sidebar from "@/components/Sidebar/Sidebar";
import FileActions from "@/components/FileActions/FileActions";
import { SearchProvider } from '@/contexts/SearchContext';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SearchProvider>
      <main className="" data-testid="home-page">
        <div className="flex mt-12">
          <Sidebar />
          <div className="flex-1">
            <FileActions />
            <div id="main" className="w-full">
              {children}
            </div>
          </div>
        </div>
      </main>
    </SearchProvider>
  );
}
